# resources/EVENTS.py

ENGINE_BOOT = "ENGINE_BOOT"
ENGINE_INIT = "ENGINE_INIT"
ENGINE_READY = "ENGINE_READY"
ENGINE_TICK = "ENGINE_TICK"
ENGINE_SHUTDOWN = "ENGINE_SHUTDOWN"
ENGINE_ERROR = "ENGINE_ERROR"
ENGINE_FATAL_ERROR = "ENGINE_FATAL_ERROR"
MOD_DISCOVERED = "MOD_DISCOVERED"
MOD_LOADED = "MOD_LOADED"
MOD_INITIALIZED = "MOD_INITIALIZED"
MOD_ERROR = "MOD_ERROR"
MOD_MANIFEST_ERROR = "MOD_MANIFEST_ERROR"
MOD_DEPENDENCY_ERROR = "MOD_DEPENDENCY_ERROR"
MOD_CONFLICT = "MOD_CONFLICT"
LOG_EVENT = "LOG_EVENT"

EVENTS = (
    ENGINE_BOOT,
    ENGINE_ERROR,
    ENGINE_FATAL_ERROR,
    ENGINE_INIT,
    ENGINE_READY,
    ENGINE_SHUTDOWN,
    ENGINE_TICK,
    MOD_CONFLICT,
    MOD_DEPENDENCY_ERROR,
    MOD_DISCOVERED,
    MOD_ERROR,
    MOD_INITIALIZED,
    MOD_LOADED,
    MOD_MANIFEST_ERROR,
    LOG_EVENT,
)
